### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by edvilme** [Stanford-Mobisocial-IoT-Lab/almond-cloud#238]
I am just getting started with the Web Almond API. 
My understanding is that the users log into their account and calling the url
`https://almond.stanford.edu/me/api/oauth2/authorize?response_type=code&client_id=MY_CLIENT_ID&redirect_uri=REDIRECT_URI`
Will return a code that should be used in the POST request to 
`https://almond.stanford.edu/me/api/oauth2/token`
Which will return a token to be used in 
`https://almond.stanford.edu/me/api/conversation`

However, when I try accessing the URL through the browser, I get an error page saying that the code is undefined. Is this a bug, or am I missing something?

Thanks in advance

**Comment by gcampax** [comment]
Thanks for your report, looking at our logs, it seems that you have found an actual bug:
> Mar 14 07:49:02 thingpedia1 node[4438]: GET /me/api/oauth2/authorize?response_type=code&client_id=e296adf4ee85476f&redirect_uri=https://example.com 500 8.322 ms - 5053
Mar 14 07:49:02 thingpedia1 node[4438]: at process._tickDomainCallback (internal/process/next_tick.js:219:9)
Mar 14 07:49:02 thingpedia1 node[4438]: at _combinedTickCallback (internal/process/next_tick.js:132:7)
Mar 14 07:49:02 thingpedia1 node[4438]: at flush (/opt/thingengine/node_modules/q/q.js:125:13)
Mar 14 07:49:02 thingpedia1 node[4438]: at runSingle (/opt/thingengine/node_modules/q/q.js:137:13)
Mar 14 07:49:02 thingpedia1 node[4438]: at /opt/thingengine/node_modules/q/q.js:624:44
Mar 14 07:49:02 thingpedia1 node[4438]: at Promise.promise.promiseDispatch (/opt/thingengine/node_modules/q/q.js:816:13)
Mar 14 07:49:02 thingpedia1 node[4438]: at self.promiseDispatch.done (/opt/thingengine/node_modules/q/q.js:883:30)
Mar 14 07:49:02 thingpedia1 node[4438]: at _fulfilled (/opt/thingengine/node_modules/q/q.js:854:54)
Mar 14 07:49:02 thingpedia1 node[4438]: at db.withClient.then (/opt/thingengine/routes/oauth2.js:217:13)
Mar 14 07:49:02 thingpedia1 node[4438]: at verifyScope (/opt/thingengine/routes/oauth2.js:190:23)
Mar 14 07:49:02 thingpedia1 node[4438]: TypeError: scopes is not iterable

This said, the bug is caused by not passing `scope=` in the query part of the `/authorize` URL. Adding that should prevent the error.

By the way, this should be documented in the Web Almond API, which has not been updated since we revamped our OAuth implementation in #139. Feel free to open a separate issue or PR for that.

**Comment by edvilme** [comment]
Hi, thank you very much. Will do on the following days. Which values should I include in the scope param?

**Comment by gcampax** [comment]
It depends on what you checked when you created the client_id, and which permission you want to request from the users.
Possible values are:
- `profile`: see the user's profile
- `user-read`: read active commands and devices
- `user-read-results`: read results of active commands
- `user-exec-command`: execute thingtalk (includes web almond access)
- `user-sync`: cloud sync (dump credentials)
- `developer-read`: read unapproved devices (equivalent to a developer key)
- `developer-upload`: upload new devices
- `developer-admin`: modify thingpedia organization settings, add/remove members
