### ISSUE TITLE
example values for parameters

### ISSUE THREAD

**Issue by rayslxu** [Stanford-Mobisocial-IoT-Lab/almond-cloud#7]
add a new field: example values for parameters for all interfaces
- use them to generate synthetic sentences for bootstrapping
- as hints in slot filling ui

**Comment by gcampax** [comment]
I was thinking we could actually store them inside the example sentences (with some new syntax), which would avoid changing the db schema.
But either way is fine.

One question: do we need more than one example value per argument?
I feel like we should ask for at least 3 or something. But I don't want to clutter the already ugly JSON editor...

**Comment by rayslxu** [comment]
@gcampax 
I don't think that's a good idea to store them in examples:
- one parameter appears in different examples 
- some parameters don't appear in the examples but should have example value
- maybe there are some parameters you don't really want users to use them (like "link" in bing search), so in this case, no example value can indicate that we should not randomly generate value for that in synthetic sentences

I also feel like we should ask for more, but I don't know exactly why that will be useful though. 

yeah, the current editor is truely ugly.... but consider we gonna have more things in the json, it probably won't be a good idea to use text editor to replace the buttons.

**Comment by gcampax** [comment]
The fact that the same parameter appears in many examples is why I would like to see the values in the examples: it might be that different sentence structures yield different example values to keep the sentence "natural".
In fact, I'm thinking more about the grayed out suggestion text in slot filling than the synthetic sentences for paraphrasing, which have slightly different requirements, to make sure they get paraphrased to the right thing.

Now, I can't think of a specific example in my mind. It might be more prevalent in languages like German, where you have cases and you need different articles for different adjuncts. But I wonder how we would fare with those cases, or if those cases matter at all, given that we're talking about quoted strings / direct speech, not coreferences.


As for parameters that don't appear in the examples, the intention is that those parameters would benefit from contains/greater than/less than comparison instead of equal comparison. How would you choose the meaningful operators in that cases? Randomly as now?

I think asking for more will be useful just because it will give more variety to the turkers. More variety in the synthetic should cause more variety in the output. That's why we have usually more than one hardcoded value in the script.

In any case, the biggest argument for not putting them in the examples is that for synthetic generation we don't use the examples at all.

(And in fact I wonder if we should use the thingpedia examples instead of the confirmations, and have even more synthetic variety. Heck, maybe we would find even meaningful synthetic data to directly train on).


Are you going to work on this, or shall I do it? I can help you get started if you want.
(It's tricky because the storage format for the JSON is not exactly intuitive)

**Comment by gcampax** [comment]
As it happens, we will need some form of this for the quote removal project (so far, it's been hacked)

**Comment by gcampax** [comment]
Upping this. We need to work on this because we're pushing the quote-free models to prod, and many Thingpedia functions are not covered by the lists of parameter values we have.
